const allAPClasses = [
  'AP Art History',
  'AP Biology',
  'AP Calculus AB',
  'AP Calculus BC',
  'AP Chemistry',
  'AP Chinese Language and Culture',
  'AP Computer Science A',
  'AP Computer Science Principles',
  'AP English Language and Composition',
  'AP English Literature and Composition',
  'AP Environmental Science',
  'AP European History',
  'AP French Language and Culture',
  'AP German Language and Culture',
  'AP Government and Politics: Comparative',
  'AP Government and Politics: U.S.',
  'AP Human Geography',
  'AP Italian Language and Culture',
  'AP Japanese Language and Culture',
  'AP Latin',
  'AP Macroeconomics',
  'AP Microeconomics',
  'AP Music Theory',
  'AP Physics 1',
  'AP Physics 2',
  'AP Physics C: Electricity and Magnetism',
  'AP Physics C: Mechanics',
  'AP Psychology',
  'AP Spanish Language and Culture',
  'AP Spanish Literature and Culture',
  'AP Statistics',
  'AP Studio Art: 2-D Design',
  'AP Studio Art: 3-D Design',
  'AP Studio Art: Drawing',
  'AP U.S. History',
  'AP World History',
];

export default allAPClasses;
