const allUCSCClasses = [
  'MATH 3: Precalculus',
  'MATH 19A: Calculus for Science, Engineering, and Mathematics',
  'MATH 19B: Calculus for Science, Engineering, and Mathematics',
  'MATH 23A: Vector Calculus',
  'MATH 23B: Vector Calculus', 
  'AM 10: Mathematical Methods for Engineers I',
  'AM 20: Mathematical Methods for Engineers II',
  'AM 30: Mathematical Methods for Engineers III',
  'STAT 131: Introduction to Probability Theory',
  'CSE 20: Beginning Programming in Python',
  'CSE 30: Programming Abstractions: Python',
  'CSE 12: Computer Systems and Assembly Language and Lab', 
  'CSE 13S: Computer Systems and C Programming',
  'CSE 16: Applied Discrete Mathematics', 
  'PHYS 5A/L: Introduction to Physics I', 
  'PHYS 5C/N: Introduction to Physics III', 
  'PHYS 5B/M: Introduction to Physics II',
  'PHYS 5D: Introduction to Physics IV', 
  'CSE 100/L: Logic Design', 
  'CSE 101: Introduction to Data Structures and Algorithms',
  'CSE 102: Introduction to Analysis of Algorithms',
  'CSE 103:Computational Models', 
  'CSE 107:Probability and Statistics for Engineers', 
  'CSE 113:Parallel and Concurrent Programming', 
  'CSE 120:Computer Architecture', 
  'CSE 125:Logic Design with Verilog', 
  'CSE 130:Principles of Computer Systems Design',
  'CSE 150:  Introduction to Computer Networks', 
  'CSE 156/L:  Network Programming',
  'CSE 185E:  Technical Writing for Computer Science and Engineering', 
  'ECE 13:  Computer Systems and C Programming', 
  'ECE 30:  Engineering Principles of Electronics', 
  'ECE 80T:  Modern Technology and How It Works',
  'ECE 101/L:  Introduction to Electronic Circuits', 
  'ECE 102/L:  Properties of Materials', 
  'ECE 103/L:  Signals and Systems',
  'ECE 135/L:  Electromagnetic Fields and Waves',
  'ECE 151:  Communications Systems', 
  'ECE 171:  Analog Electronics', 
  'CSE 111:  Advanced Programming', 
  'CSE 121:  Embedded System Design', 
  'CSE 122:  Introduction to VLSI Digital System Design', 
  'CSE 220:  Computer Architecture', 
  'ECE 103/L:  Signals and Systems', 
  'CSE 112 or 114A:  Comparative Programming Languages',
  'STAT or CSE 131 or 107:  Introduction to Probability Theory'
]

export default allUCSCClasses;
